### ISSUE TITLE
[Bug] 学生页面加载时会出现超过100%的情况

### ISSUE THREAD

**Issue by pfjhyyj** [Mark9804/blue-archive-story-viewer#122]
### 问题描述

学生页面加载时会出现超过100%的情况
![image](https://user-images.githubusercontent.com/15180163/214060904-ba8ec73e-a429-4b25-be30-053884dfc29f.png)

### 问题位置

https://blue-archive.io/archive

https://github.com/ba-archive/blue-archive-story-viewer/blob/c534956a262692b6a7a99845b567a4fc02f0452c/src/components/momotalk/MomotalkContainer.vue#L71-L75

**Comment by pfjhyyj** [comment]
progressEvent.total为0导致进度条超出100
与cloudflare使用content-encoding=br有关？

**Comment by mark9804** [comment]
> 与cloudflare使用content-encoding=br有关？

在使用 gzip 的 https://ba-archive.github.io/ 上面也能复现的

**Comment by mark9804** [comment]
> We’re compressing it on the fly and don’t know what the length will be for the object when we return the headers.
> https://community.cloudflare.com/t/no-content-length-header-when-response-is-compressed/134475

如果这个问题比较普遍的话，我觉得干脆加载方式改成骨骼屏好了。因为 `progress.total` 要从 response headers 的`Content-Length` 获取，header 没有的话我想不出一个显示具体百分比的做法

**Comment by mark9804** [comment]
也算是修了
