### ISSUE TITLE
[Enhancement] 追加一个学生 loading 头像

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#145]
### 功能描述

![image](https://user-images.githubusercontent.com/55832499/222879077-046d6a5c-9152-44fd-bf73-3b0d211fcd53.png)
rt，有时候加载比较慢，学生头像不能很快的加载出来
而显示的就是一个小框包住名字
那么如果加一个默认头像，让他先用默认头像加载，感受也许会好一些？
（又或者固定box的大小，以至于让他不会变成这么小的框）

**Comment by mark9804** [comment]
在冲刺 player 上线，这个看看小雪更新的时候能不能做进去

**Comment by mark9804** [comment]
issue 会自动关闭的，我很享受合并入主线的时候一下子 ~~像割韭菜一样~~ 少掉一片 issue 的感觉，请不要剥夺这份小小的乐趣

**Comment by xiaofeiTM233** [comment]
> issue 会自动关闭的，我很享受合并入主线的时候一下子 ~像割韭菜一样~ 少掉一片 issue 的感觉，请不要剥夺这份小小的乐趣

抱歉，我太急了（其实是看岔了以为是主分支修了但是没关）
谢谢，下次注意
