### ISSUE TITLE
[Bug] 若在加载资源前的播放器点下自动播放，之后的自动播放失效

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#151]
### 问题描述

rt
![image](https://user-images.githubusercontent.com/55832499/223025357-34832fb1-c29c-4990-a3e2-4013e68ef176.png)
![image](https://user-images.githubusercontent.com/55832499/223025417-84ba856d-e6dd-4939-b29e-b8d13ff3ce18.png)

### 问题位置

https://blue-archive.io/mainStory/11000

### 复现流程

在加载资源界面出现前出现的播放器内点击自动播放

**Comment by xiaofeiTM233** [comment]
建议：不提前加载播放器

**Comment by mark9804** [comment]
实际修复：把 auto 按钮隐藏了

**Comment by mark9804** [comment]
现在在加载时看不到auto了，所以也算修了
