### ISSUE TITLE
[Enhancement] 暗色模式优化

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#152]
### 功能描述

![image](https://user-images.githubusercontent.com/55832499/223028653-d2434b87-74e7-4a7a-b472-4e65f11a100f.png)
↑这个是最显著的（
![image](https://user-images.githubusercontent.com/55832499/223028792-b7ea3bfc-50fa-4534-b02f-d4b72b3fab9d.png)
↑这个也基本看不清
![image](https://user-images.githubusercontent.com/55832499/223028946-32d50b7e-e2ec-4c55-b20f-dffcdcff4812.png)
↑过暗了

其余的还好

### 具体操作

css改一下就行

**Comment by mark9804** [comment]
第一个是在什么系统里面复现的？Windows 的全局暗色模式？

第二个是我的问题

后面那个之后提一下暗色模式的变量亮度

**Comment by mark9804** [comment]
1 确认是 Windows 环境下的问题，我用的 Mac 没发现

不太确定能不能修

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/9006264/223034801-917c14da-5093-4dcf-a520-26650f74d7a6.png">

**Comment by xiaofeiTM233** [comment]
> 1 确认是 Windows 环境下的问题，我用的 Mac 没发现
> 
> 不太确定能不能修
> 
> <img alt="image" width="1377" src="https://user-images.githubusercontent.com/9006264/223034801-917c14da-5093-4dcf-a520-26650f74d7a6.png">

@Mark9804 啊原来有圆角的吗（圆角也没有
其实css给里面文字加个颜色或者给他底部加个黑色背景就行
↓瞎写，证明能改罢了
![image](https://user-images.githubusercontent.com/55832499/223076778-096d82c9-ad12-492e-9d7d-dd8f12e2eaa7.png)

**Comment by xiaofeiTM233** [comment]
> 第一个是在什么系统里面复现的？Windows 的全局暗色模式？
> 
> 第二个是我的问题
> 
> 后面那个之后提一下暗色模式的变量亮度

就是左下角的暗色按钮

**Comment by mark9804** [comment]
圆角那个我想了想顿悟了，我是win11……

**Comment by xiaofeiTM233** [comment]
闲着无聊，
翻了一下，发现是css写错了（
有一个简单的修改方式
./src/components/widgets/LanguageSelector.vue

1. 直接![image](https://user-images.githubusercontent.com/55832499/224530815-fd506453-6b37-464e-a5ba-b54c3becd25f.png)
2. 懒一点![image](https://user-images.githubusercontent.com/55832499/224530453-d0ccbfc2-652f-473a-a948-9eacc8d26f80.png)
3. 干脆（此图中未格式化）![image](https://user-images.githubusercontent.com/55832499/224530599-09c88c74-4b4f-427e-9c73-2d9968be9614.png)
4. 根本上解决![image](https://user-images.githubusercontent.com/55832499/224530962-dd1da2d3-7ff6-4051-9210-639d5a7800d0.png)
5. 我的想法（此图中未格式化）![image](https://user-images.githubusercontent.com/55832499/224531118-3e8541b1-4b07-43c4-91ba-c50b252a795d.png)
6. 最终结果（已经格式化过了，直接替换进去就行）
```
<script setup lang="ts">
import { ref } from 'vue';
import { useSettingsStore } from '../../store/settings';

const languages = ref([
  {
    name: '简体中文',
    code: 'cn',
  },
  {
    name: '繁體中文',
    code: 'tw',
  },
  {
    name: '日本語',
    code: 'jp',
  },
  {
    name: 'English',
    code: 'en',
  },
  {
    name: '한국어',
    code: 'kr',
  },
  {
    name: 'ไทย',
    code: 'th',
  },
]);

const settingsStore = useSettingsStore();
const selectedLang = ref(settingsStore.getLang);

function handleLangChange(event: Event) {
  const target = event.target as HTMLSelectElement;
  settingsStore.setLang(target.value);
}
</script>

<template>
  <select
    class="language-switcher rounded-small"
    v-model="selectedLang"
    @change="handleLangChange($event)"
  >
    <option
      v-for="language in languages"
      :key="language.code"
      :value="language.code"
    >
      {{ language.name }}
    </option>
  </select>
</template>

<style scoped lang="scss">
select {
  appearance: none;
  -webkit-appearance: none;
  cursor: pointer;
  outline: none;
  border: none;
  padding: 0 0.5rem;
  color: var(--color-text-main);
  font-size: inherit;
  line-height: inherit;
  font-family: inherit;
  text-align: center;
  display: flex;
  flex-direction: row;
  align-items: center;
  transition: all 0.375s ease-in-out;
  box-shadow: var(--style-switch-track-shadow);
  background-color: var(--color-switch-track);
  width: fit-content;
  user-select: none;
}
</style>
```
↑图片都仅作演示
此方案在没有其他多选框需要一起改css的前提下进行
具体整看着办吧qwq
@Mark9804

**Comment by xiaofeiTM233** [comment]
另外，暗色模式状态在刷新后会被清除
![image](https://user-images.githubusercontent.com/55832499/224531234-e54ddfbd-e93d-43ad-8683-1715c8f004f9.png)
_（已经为暗色模式但界面仍是亮色模式的截图）_

**Comment by mark9804** [comment]
你来我组吧😭

两个问题都解决了，等待下一个合并窗口

**Comment by xiaofeiTM233** [comment]
暗色模式文字颜色适配
./src/style.scss
### 1
![image](https://user-images.githubusercontent.com/55832499/224532562-2fc086a6-32ea-4a78-ada2-6346e89dfad8.png)
↑那个空行是为了与亮色照应，加不加无所谓
#### 效果

前![image](https://user-images.githubusercontent.com/55832499/224532899-8453238e-64ed-448e-99b3-817f0ec2b0b3.png)后![image](https://user-images.githubusercontent.com/55832499/224533113-462476f8-2f8d-409f-a1cd-4449eac6e086.png)

### 2
如果接受，建议加上↓
```
* {
    color: var(--color-text-main);
}
```
如果不接受，把*改成a就只改a标签就行（如果有更好的颜色也行）
#### 效果
前
![image](https://user-images.githubusercontent.com/55832499/224533229-83964174-a9bd-4b04-81c6-282cf60e088e.png)
![image](https://user-images.githubusercontent.com/55832499/224533162-610b6cf1-263d-4127-a138-b416ef9bf85e.png)
后
![image](https://user-images.githubusercontent.com/55832499/224533246-636fd752-8354-48d9-968b-dfc5bfc327a3.png)
![image](https://user-images.githubusercontent.com/55832499/224533202-1bd23287-6f27-49b4-9fe2-df557f7d9acf.png)

### 3
一个bug![image](https://user-images.githubusercontent.com/55832499/224533290-1263102e-6f90-41d2-9268-3ab48354e622.png)
span标签没有过渡
有空加上就是
```
span {
  transition: color .375s ease-in-out;
}
```

### 4
这里写的是
`--color-primary-button: #ecbbd0;`
但是因为修改这个会导致按钮颜色也变化
后面实装的时候记得调一下或者干脆换成别的

#### 效果
前![image](https://user-images.githubusercontent.com/55832499/224533370-64d5f2eb-0e8d-49fe-8147-8ee30f7e2930.png)
后![image](https://user-images.githubusercontent.com/55832499/224533351-96d8819d-6d40-4667-81c8-acec70e1bbdc.png)

**Comment by xiaofeiTM233** [comment]
> 你来我组吧sob
> 
> 两个问题都解决了，等待下一个合并窗口

把刚刚这个也加上吧（

**Comment by xiaofeiTM233** [comment]
> 暗色模式文字颜色适配 ./src/style.scss
> 
> ### 1
> ![image](https://user-images.githubusercontent.com/55832499/224532562-2fc086a6-32ea-4a78-ada2-6346e89dfad8.png) ↑那个空行是为了与亮色照应，加不加无所谓
> 
> #### 效果
> 前![image](https://user-images.githubusercontent.com/55832499/224532899-8453238e-64ed-448e-99b3-817f0ec2b0b3.png)后![image](https://user-images.githubusercontent.com/55832499/224533113-462476f8-2f8d-409f-a1cd-4449eac6e086.png)
> 
> ### 2
> 如果接受，建议加上↓
> 
> ```
> * {
>     color: var(--color-text-main);
> }
> ```
> 
> 如果不接受，把*改成a就只改a标签就行（如果有更好的颜色也行）
> 
> #### 效果
> 前 ![image](https://user-images.githubusercontent.com/55832499/224533229-83964174-a9bd-4b04-81c6-282cf60e088e.png) ![image](https://user-images.githubusercontent.com/55832499/224533162-610b6cf1-263d-4127-a138-b416ef9bf85e.png) 后 ![image](https://user-images.githubusercontent.com/55832499/224533246-636fd752-8354-48d9-968b-dfc5bfc327a3.png) ![image](https://user-images.githubusercontent.com/55832499/224533202-1bd23287-6f27-49b4-9fe2-df557f7d9acf.png)
> 
> ### 3
> 一个bug![image](https://user-images.githubusercontent.com/55832499/224533290-1263102e-6f90-41d2-9268-3ab48354e622.png) span标签没有过渡 有空加上就是
> 
> ```
> span {
>   transition: color .375s ease-in-out;
> }
> ```
> 
> ### 4
> 这里写的是 `--color-primary-button: #ecbbd0;` 但是因为修改这个会导致按钮颜色也变化 后面实装的时候记得调一下或者干脆换成别的
> 
> #### 效果
> 前![image](https://user-images.githubusercontent.com/55832499/224533370-64d5f2eb-0e8d-49fe-8147-8ee30f7e2930.png) 后![image](https://user-images.githubusercontent.com/55832499/224533351-96d8819d-6d40-4667-81c8-acec70e1bbdc.png)

@Mark9804 有空看看

**Comment by mark9804** [comment]
在看了在看了，changelog都不知道要怎么写了😭

**Comment by mark9804** [comment]
弹性装甲的暗色模式颜色是多少，我要开偷了
