### ISSUE TITLE
[Enhancement] 关于iOS全屏

### ISSUE THREAD

**Issue by ghost** [Mark9804/blue-archive-story-viewer#153]
### 功能描述

关于iOS的全屏

### 具体操作

iOS的alook浏览器有全屏模式，不知能否适配
![91C89EC8-77CB-4F5B-8216-70267D12EFBE](https://user-images.githubusercontent.com/127098456/223081837-9b3fa844-5147-42c8-9755-7082f810b6e5.jpeg)
附Alook砸壳ipa
https://wwff.lanzoum.com/i9ig90pfpyza
密码:bkjf

**Comment by AKAAIR** [comment]
![Uploading 42B114BA-3E9B-47E5-8A0A-41BCF5768B7E.png…]()

**Comment by ghost** [comment]
![1F9A0D76-6CF0-448A-81A8-6046CC46C47A](https://user-images.githubusercontent.com/127098456/223083838-96fa1e5c-b27f-47d0-8b68-451d13296414.png)

**Comment by mark9804** [comment]
Alook 浏览器我自己设备上有，不过还是感谢砸壳。

据我之前的了解，alook 的一些功能是自己内部通过一些比较取巧的方法实现的（因为苹果并没有提供类似功能），所以我不太确定能不能成功适配，不过会尝试一下

**Comment by mark9804** [comment]
我在我的 alook 17.2 上无法全屏，请问您用的是什么版本的alook？

**Comment by ghost** [comment]
> 我在我的 alook 17.2 上无法全屏，请问您用的是什么版本的alook？

怎样的无法全屏呢，我使用的是15.2  将手机横屏

**Comment by ghost** [comment]
> 我在我的 alook 17.2 上无法全屏，请问您用的是什么版本的alook？

我的步骤是工具箱进入全屏-横屏-刷新-进入剧情
是否使用了PCUA，尝试请求移动版网站

**Comment by mark9804** [comment]
alook 似乎播放器的全屏请求会被拦截，可能和 https://github.com/ba-archive/ba-story-player/issues/70 的触发原理类似，会尝试排查一下

**Comment by mark9804** [comment]
这个问题我们会提到 vite-pwa 那边去看看是不是那边的问题，如果依然不是的话我们可能要提去 edge 和 alook 那边，可能很长时间不会跟进

**Comment by mark9804** [comment]
不好意思，alook 过于特殊，经过多次测试实在找不到支持方式。本周末预计放出一个基本支持手机端 Safari 全屏的版本，到时候麻烦再测试一下
