### ISSUE TITLE
momotalk 等待玩家完成羁绊剧情后继续

### ISSUE THREAD

**Issue by mark9804** [Mark9804/blue-archive-story-viewer#159]

**Comment by xiaofeiTM233** [comment]
可以展示羁绊剧情之后直接暂停
然后在卡片![image](https://user-images.githubusercontent.com/55832499/224481151-d9dbbad6-f1ff-4f70-9f48-196d2330aa39.png)的右上角增加一个跳过按钮，这样可以不看剧情继续播放
等待看完剧情什么的以后再做

**Comment by mark9804** [comment]
> 可以展示羁绊剧情之后直接暂停 然后在卡片![image](https://user-images.githubusercontent.com/55832499/224481151-d9dbbad6-f1ff-4f70-9f48-196d2330aa39.png)的右上角增加一个跳过按钮，这样可以不看剧情继续播放 等待看完剧情什么的以后再做

这个想法确实不错
