### ISSUE TITLE
enhancement: 完成选择后再显示羁绊事件

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#162]
### 问题描述

![image](https://user-images.githubusercontent.com/55832499/224460432-93369972-b4dc-494f-8dac-2dc16c3056d5.png)
rt，还未选择选项就弹出羁绊事件了
并且
左侧![image](https://user-images.githubusercontent.com/55832499/224460572-bc5648af-97bd-4685-879b-6038be1247ba.png)
是确实没有头像还是意义不明的分段？

### 问题位置

/archive/10063/momotalk

### 复现流程

正常播放小雪第二段momotalk

**Comment by mark9804** [comment]
> 还未选择选项就弹出羁绊事件了

在写了在写了

> 是确实没有头像还是意义不明的分段？

是故意的

![2D06D55D-10B2-4324-9681-D2F81D4A8B24_1_201_a](https://user-images.githubusercontent.com/9006264/224462012-5248f500-9afb-4a95-a0e4-b5ff6544aea6.jpeg)
