### ISSUE TITLE
[Enhancement] 快速尝鲜

### ISSUE THREAD

**Issue by luckyray-fan** [Mark9804/blue-archive-story-viewer#163]
### 功能描述

流程: 
- 发布当天六点解完包后, 机翻加简单校对完一章发一章
- 公告处, 当天发完机翻校对第一章后, b站发布尝鲜公告, 之后完全翻译好后再发一下完全翻译公告

### 具体操作

- 为了避免频繁打包发线上, 资源加载改成拉取配置文件, 根据配置文件渲染可以查看的剧情
- 翻译工具改成可以加载story, 边翻译校对的同时可以看是否播放有误, 播放器是否会卡死
- 新增特效等和完全翻译一块补上, 如果特效赶不上则先发布翻译, 后续补上特效

**Comment by luckyray-fan** [comment]
配置文件可以用对象存储, 这个免费额度应该就可以 cover

**Comment by Mark9804** [comment]
主站还是保持高质量翻译，另外开一个子站点，想优先看机翻可以看那边

**Comment by mark9804** [comment]
> 配置文件可以用对象存储

又要重构了是吗😭

**Comment by mark9804** [comment]
我想了一下，机翻可以整合进我们的工作流提高效率，但是不能直接发布

这样和拿个uu翻译器之类的开屏幕翻译然后录屏上传没太大区别了
