### ISSUE TITLE
故事包提案：story bundle

### ISSUE THREAD

**Issue by notnotype** [Mark9804/blue-archive-story-viewer#164]
### 起因

1. 便于更好的分类组织剧情
2. **便于自定义剧情的创作与传播**
3. 便于剧情的下载
4. 减少了 ScenarioBGNameExcelTable.json 等文件的访问（不必要为了查找某个音效而把所有音效映射表下载下来）

### 构成

一个故事包包括了播放一个故事所需要的全部文件：

- 对应角色的 momotalk （如果有）
- 所有出场人物的 spr
- 对应角色的 live2d （如果有）
- 相关剧情脚本文件
- 剧情相关音频文件

### 故事包可以分为离线故事包和在线故事包

**离线故事包**

包括了所有通用资源，比如按钮点击特效，某个表情图片

**在线故事包**

所有的资源，比如按钮特效，按钮音效，角色spr提供一个url供用户下载，只存储剧情相关脚本文件和momotalk

**为什么？**

如果用户有下载需求，可以使用离线故事包。
但是如果全部使用离线故事包，有些人物的spr在多个离线故事包出现了会导致额外的流量费用，故引入了在线故事包
在线故事包保证了小尺寸文件如：剧情脚本、momotalk独立，但是共用一套在线cdn减少流量损耗。

在这里为了之后的自定义剧情先提了一下，还有许多细节有待完善

**Comment by mark9804** [comment]
高看我的技术了朋友
