### ISSUE TITLE
[Bug] 浏览器momotalk对话历史丢失

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#168]
### 问题描述

浏览器（不安装应用）播放剧情再切回来
momotalk对话历史就会丢失
但实测安装为应用后无此问题
不清楚是不是浏览器的问题

### 问题位置

仅在edge浏览器做了测试，别的没试

### 复现流程

点击前往羁绊剧情再返回momotalk

**Comment by mark9804** [comment]
泻药，edge 自己实现有问题，我们不背锅

https://github.com/ba-archive/ba-story-player/issues/70

**Comment by xiaofeiTM233** [comment]
> 泻药，edge 自己实现有问题，我们不背锅
> 
> [ba-archive/ba-story-player#70](https://github.com/ba-archive/ba-story-player/issues/70)

~~经测，Chromium大环境下都有此问题，firefox并无~~
~~edge：我虽然烂，但也不能让我背Chromium的锅吧~~
我收回，是master分支不行，dev分支可以
没有推送
我自己几个分支来回串搞混了
抱歉

**Comment by mark9804** [comment]
如果是 dev 可以的话，应该和这个有关 c9dd567b1c526c6c1ac86f26cd82be75bd67da56
