### ISSUE TITLE
[Bug] 开始播放后再进入播放会刷新页面

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#169]
### 问题描述

rt
点击“明白”后开始播放剧情后
切出去再重新进入任一剧情播放器都会刷新页面
不清楚是不是有意的
如果不是有意的，那就修一下
如果是有意的，希望能换一个方式（

### 问题位置

剧情

### 复现流程

点击“明白”后开始播放剧情后，切出去再重新进入任一剧情播放页

**Comment by mark9804** [comment]
是有意的，我们使用了一种很朴素的方式避免一些很严重的 bug

之后会解决这个问题

**Comment by mark9804** [comment]
![image](https://user-images.githubusercontent.com/9006264/224484663-3fd13ca6-fcab-4b31-bd00-2f5978a84aa5.jpeg)

**Comment by xiaofeiTM233** [comment]
> <details>
> 
> <img src="https://user-images.githubusercontent.com/9006264/224484663-3fd13ca6-fcab-4b31-bd00-2f5978a84aa5.jpeg" width="360" />
> </details>

真是个简单粗暴的解决方案（
