### ISSUE TITLE
[Enhancement] 剧情全覆盖

### ISSUE THREAD

**Issue by luckyray-fan** [Mark9804/blue-archive-story-viewer#170]
### 功能描述

后续主线剧情开发进度:
1. 第三章
2. 最终章
3. 第一章
4. 第二章
5. 第四章

### 具体操作

请敲定发布时间

**Comment by mark9804** [comment]
别敲定时间了，再敲真坐牢了😭

真要我敲的话就 4 周发布一个章节吧，我估计越到后面发布会越轻松，因为大部分特效都会被覆盖到

**Comment by luckyray-fan** [comment]
草我觉得大头就都是翻译啊, 特效花几个时间啊

**Comment by luckyray-fan** [comment]
可以先启动, 然后慢慢看下具体耗费时间

**Comment by luckyray-fan** [comment]
把国际服目前的进度, 通过繁中润色覆盖追上, 先刷全量再追日服增量 @Mark9804 
- 主线, 按照上文, 除最终章外共 195 节
- 角色剧情, 按照人气顺序来, 约计 134 名学生, 每人往上算5节好感剧情, 共 670 节
- 以上合计 865 节

目前常驻翻译 5 位, 校对 1位, 如果每周每人翻译 3 节, 需要 57 周, 每节 2小时左右, 校对八成校不了这么多
如果用润色方式, 每人包括校对润色 8 节, 需要 18 周, 每节 30min 左右

当然以上都是不精确的估算, 有误差, 如果最终要定一个规划的话, 按照一周顶格 48 节的速度, 我们可以一周发布 vol.x 的一章(一般是20节左右)

**Comment by luckyray-fan** [comment]
另外剧情翻译定期做一个备份, 最好用个github库放一下

**Comment by mark9804** [comment]
备份仓库确实可以做

**Comment by luckyray-fan** [comment]
预计发布春佳代子后启动第三章 @Mark9804 #207
