### ISSUE TITLE
[Enhancement] 超分功能正式使用

### ISSUE THREAD

**Issue by luckyray-fan** [Mark9804/blue-archive-story-viewer#171]
### 功能描述

![} Q) D(V6F2PV)2JHRAELJQ](https://user-images.githubusercontent.com/38815993/224485822-d749544d-fb34-467f-8e3e-8b256dae5ac1.jpg)
![6VPRW5SJ RB`Y ~XA}8H UB](https://user-images.githubusercontent.com/38815993/224485824-86bc0ccc-cd16-46bd-a810-d89ea723972c.jpg)

### 具体操作

目前超分功能已经基本完成, 需要流水线进行配合并且正式上线

**Comment by diyigemt** [comment]
啊哈哈 https://github.com/ba-archive/ba-story-player/issues/103

**Comment by luckyray-fan** [comment]
期待一手mt的脚本 @diyigemt

**Comment by luckyray-fan** [comment]
超分范围: 人物 spine, 背景图片 
当前超分进度: 
- [x] 播放器支持开启超分 
- [x] 主应用支持设置超分
- [x] 存量图片素材支持超分, 并且上传 cdn, 预计本周末刷完当前已上线部分 spine 和所有背景图片
- [ ] 流水线增量支持超分

**Comment by mark9804** [comment]
已完成

**Comment by diyigemt** [comment]
流水线增量啥时候支持的超分，我怎么不知道

**Comment by mark9804** [comment]
我的我的 还以为做完了
