### ISSUE TITLE
[Bug] 润色后的momotalk和剧情又不一样了

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#176]
### 问题描述

![image](https://user-images.githubusercontent.com/55832499/224505405-ee563fe8-0517-412d-840d-c0dde3c8839a.png)
![image](https://user-images.githubusercontent.com/55832499/224505414-514c4a63-87fe-487e-bf81-70ef5d7d458f.png)

![image](https://user-images.githubusercontent.com/55832499/224505477-47b4347b-5ebb-434a-8a56-edb3995e0c72.png)https://github.com/ba-archive/blue-archive-story-viewer/commit/4f3dd88b46e0deaf193eb1df3cd9c72cc3786a26

### 问题位置

小雪

**Comment by mark9804** [comment]
这部分打算重构一下，当初没考虑扩展性，现在读取是从三个地方读的，，有点离谱

**Comment by xiaofeiTM233** [comment]
新问题
问题地方./public/story/favor/10063/index.yml
![image](https://user-images.githubusercontent.com/55832499/224908321-66fb3b9c-34b0-4b40-a246-20041dee8337.png)
![image](https://user-images.githubusercontent.com/55832499/224908006-1896c9d7-d692-418b-8a3d-fd518827bf34.png)
翻译内容不一致
![image](https://user-images.githubusercontent.com/55832499/224908289-96ecae08-8e30-4027-bab6-02f5123e25c6.png)

**Comment by mark9804** [comment]
预计重构之后只会剩下一处入口

**Comment by mark9804** [comment]
Duplicate of #188

**Comment by mark9804** [comment]
这个我觉得重新刷新一下能解决

**Comment by xiaofeiTM233** [comment]
![image](https://user-images.githubusercontent.com/55832499/226910001-50543d88-849c-43e1-a636-e9d0501e2797.png)
![image](https://user-images.githubusercontent.com/55832499/226910034-a7d6ea60-40b5-42f8-acf7-e8353e9e7899.png)

**Comment by mark9804** [comment]
果咩那塞 没注意

**Comment by mark9804** [comment]
两拨人翻的确实有这问题

**Comment by xiaofeiTM233** [comment]
翻译矫正现在排在第几位捏
感觉有必要把翻译都核对一遍
但是优先级感觉会比剧情翻译要低（？）
![image](https://user-images.githubusercontent.com/55832499/226987901-4d8d00cf-f53f-47a3-8809-3c43e140d153.png)
比如这个“课”字
要不就有要不就没有吧
怎么有的有，有的没有（

**Comment by mark9804** [comment]
校对人手不够，你看到的99%的翻译都是我校的

**Comment by mark9804** [comment]
b6ee807
