### ISSUE TITLE
后端功能支持讨论区

### ISSUE THREAD

**Issue by mark9804** [Mark9804/blue-archive-story-viewer#178]
- 根据文字搜索对应剧情并跳转，player dev 分支已经实现自由跳转
- 接入 [CLIP](https://github.com/openai/CLIP)，实现「使用自然语言搜索背景图像，并返回使用了这（几）张图像的对应剧情」
- 用户自定义剧情的存储和链接生成

**Comment by notnotype** [comment]
- [x] 实时在线人数
- [x] 总访问人数
- [x] 用户登录（接入oauth2）
- [ ] 自定义剧情浏览、排行榜
- [ ] 评论、弹幕（

**Comment by mark9804** [comment]
认真的吗

> * [x]  实时在线人数
> * [x]  总访问人数
> * [x]  用户登录（接入oauth2）
> * [ ]  自定义剧情浏览、排行榜
> * [ ]  评论、弹幕（
