### ISSUE TITLE
[Enhancement] i18n修正zh

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#179]
### 功能描述

_作为一个中国人，不应该刻意把湾湾独立
cn和tw是一体！_

啊就是简单区分简中繁中而不是区分大陆和台湾

### 具体操作

cn改成zh-hans，tw改成zh-hant

**Comment by mark9804** [comment]
nexon 就是这么写的，我们也没办法

文字上区分就可以了，我这边已经刻意弱化地区了

<img width="122" alt="image" src="https://user-images.githubusercontent.com/9006264/224533840-bac77379-1593-4820-9781-76ae4c49a9b0.png">

**Comment by xiaofeiTM233** [comment]
这不对吧，ba可没有简中哦

**Comment by mark9804** [comment]
nexon繁中用的字段是 TextTW，那我简中加一个 TextCN 很自然

数据结构已经定下来了，基本不可能改了

**Comment by xiaofeiTM233** [comment]
> nexon繁中用的字段是 TextTW，那我简中加一个 TextCN 很自然
> 
> 数据结构已经定下来了，基本不可能改了

没事，其实不改也没多大关系
我是看到某个东西写的zh-hans和zh-hant才突发奇想的（

**Comment by mark9804** [comment]
如果是我这边的 zh-hans 和 hant 的话，那应该是 localeCompare 里面的标准参数

其他的我没有印象，全部是跟着 nexon 数据结构走的

**Comment by notnotype** [comment]
还有这么多语言变体：
![image](https://user-images.githubusercontent.com/53962334/224534939-0698920b-10b1-4245-8526-8a34905fa8ff.png)
https://zh.wikipedia.org/wiki/Help:%E5%AD%97%E8%AF%8D%E8%BD%AC%E6%8D%A2%E7%9A%84%E6%A8%A1%E5%BC%8F%E9%80%89%E6%8B%A9%E8%AF%B4%E6%98%8E

**Comment by xiaofeiTM233** [comment]
https://translatewiki.net
