### ISSUE TITLE
早期角色的 momotalk 好感剧情 NextGroupId 为 0 导致点击前往好感剧情后也无法继续

### ISSUE THREAD

**Issue by mark9804** [Mark9804/blue-archive-story-viewer#193]
测试：黑猫剧情第五段
<img width="521" alt="image" src="https://user-images.githubusercontent.com/9006264/225344753-0b86c702-00b5-4c7d-84fe-a19ea9c15b37.png">

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/9006264/225343918-7700b7b6-f9bc-405a-87c2-0f6128d806f5.png">

期望表现：点击“继续阅读”，向父组件回传一个 `nextMessage(不为0的 NextGroupId)` 事件，父组件继续推送消息

实际表现：`NextGroupId` 为 `0`，无法找到下一条消息

正确进行例：小雪好感剧情第一段
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/9006264/225343935-27ba480f-139c-4709-aee7-ac210a021c3c.png">

**Comment by ourandream** [comment]
afdf1cf

**Comment by ourandream** [comment]
> [afdf1cf](https://github.com/ba-archive/blue-archive-story-viewer/commit/afdf1cfd5623bebb67f915781c23d166133a9e0d)

其实更好的修改方法应该是按下选择按钮后再填入nextGroupId, 不过目前这样修应该也没有bug
