### ISSUE TITLE
Momotalk 多次点击前往剧情出现重复对话

### ISSUE THREAD

**Issue by mark9804** [Mark9804/blue-archive-story-viewer#194]
复现方式：狂点“前往剧情”或者“继续阅读”中的任意一个按钮
<img width="512" alt="image" src="https://user-images.githubusercontent.com/9006264/225348762-462f84a0-f8c6-47ff-8830-423a82cd3d9f.png">

**Comment by ourandream** [comment]
dd1203703e3c921d03b894dfdf56f8417ffa54d7
