### ISSUE TITLE
Momotalk 在看完剧情跳转回组件后才触发接下去的对话

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#195]
### 问题描述

点击 前往好感剧情按钮 后，momotalk的对话被重置
如：
原本
![image](https://user-images.githubusercontent.com/55832499/225760870-bb18ca7b-cd7b-4b97-9ef1-d5ba60985106.png)
（已经播放到后面来了）

重新点击后
（当然会跳转到好感剧情，然后再点回来）
![image](https://user-images.githubusercontent.com/55832499/225760997-86ee9fa3-61fe-4d43-b999-5661681ed08c.png)
_（被重置了）_

并且，会提前展示momotalk
（也就是点完前往，就会直接开始播放剧情结束后的momotalk，而不是等回来再继续播放）
~~(假装)看完剧情~~，切回来之后
![image](https://user-images.githubusercontent.com/55832499/225761368-c2de476c-12f7-4ecb-9b85-0b9004ca7e2c.png)
（这部分应该是没做吧而不是bug）

### 问题位置

momotalk

### 复现流程

点击 前往羁绊剧情 按钮

**Comment by mark9804** [comment]
哪个分支

**Comment by mark9804** [comment]
欧，这个是故意的不是不小心

都点了前往剧情了，不把后面的对话清掉有点奇怪

**Comment by mark9804** [comment]
没看完就展示momotalk是推送服务写的时候没考虑到这个需求，等重构了

**Comment by xiaofeiTM233** [comment]
> 欧，这个是故意的不是不小心
> 
> 都点了前往剧情了，不把后面的对话清掉有点奇怪

啊这，我是想着既然都没有为啥要清有点怪（
那么是否能重置功能独立出来成一个按钮？qwq

**Comment by mark9804** [comment]
感觉没有必要多这么一个按钮，如无必要勿增实体

**Comment by xiaofeiTM233** [comment]
抱歉，人傻了，忘了还能没有后续了
~~播放完剧情没有正常继续momotalk
[fix: 修复跳转到羁绊剧情界面momotalk继续播放的bug #f3a4ff9](https://github.com/ba-archive/blue-archive-story-viewer/commit/f3a4ff9d408a70edf7d3f429f3e4523abda67fb0)~~

**Comment by xiaofeiTM233** [comment]
![image](https://user-images.githubusercontent.com/55832499/226911290-f8d46115-5f56-4bfa-9188-d87c209cf50f.png)


> 播放完剧情没有正常继续momotalk [f3a4ff9](https://github.com/ba-archive/blue-archive-story-viewer/commit/f3a4ff9d408a70edf7d3f429f3e4523abda67fb0)

**Comment by mark9804** [comment]
本来就没有后续
<img width="839" alt="image" src="https://user-images.githubusercontent.com/9006264/226911873-47a8f6fa-a179-41a1-829f-0b51bb6f8a66.png">

**Comment by xiaofeiTM233** [comment]
> 本来就没有后续

抱歉，人傻了，忘了还能没有后续了（
