### ISSUE TITLE
[Enhancement] 点击前往剧情后隐藏“继续阅读”按钮

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#196]
### 功能描述

既然[perf: 点击继续阅读按钮后该按钮不会再次出现](https://github.com/ba-archive/blue-archive-story-viewer/commit/67ec2a442127a2582f3618a7887e97a72d78dd0a)
那么点击前往剧情后也隐藏这个按钮吧
![image](https://user-images.githubusercontent.com/55832499/225763493-3f821156-2186-4e10-97d1-cb3fa6473bb9.png)
再次点击就是重置对话了

### 具体操作

在跳转好感剧情按钮后面也加一串关闭按钮的js就是

**Comment by mark9804** [comment]
你说得好有道理

**Comment by xiaofeiTM233** [comment]
人傻了，忘了还能没有后续了
~~如果加上跳转并且不会自动继续播放的话，要么在继续播放之前还是不隐藏了？~~

**Comment by mark9804** [comment]
那这个就算解决了？

**Comment by xiaofeiTM233** [comment]
> 那这个就算解决了？

当时应该一并把这个关闭的

**Comment by mark9804** [comment]
好爽
<img width="224" alt="image" src="https://user-images.githubusercontent.com/9006264/226920759-c3066979-e718-4b54-b50c-f62ed300a144.png">
