### ISSUE TITLE
[Enhancement] 人气角色 小游戏

### ISSUE THREAD

**Issue by luckyray-fan** [Mark9804/blue-archive-story-viewer#211]
### 功能描述

类比于google的[小恐龙游戏](https://www.hhtjim.com/wp-content/uploads/2017/02/T-RexGame.html)等, 为某些学生开发具有他们特色的小游戏, 然后在生日的时候发布, 并匹配视频发布等
![image](https://user-images.githubusercontent.com/38815993/227582192-273a6779-e765-423c-84b4-92c0c71717a5.png)

- 比如 爱丽丝, 爱丽丝激光镭射打怪等
![image](https://user-images.githubusercontent.com/38815993/227581666-33780b97-db1b-4820-8abd-c93dfff8499e.png)

- 并且可以设置分数排行榜等
- 预计开发时间, 待定
   - 最早两周后( 超分, 中日双语上线), 如果要重构, 那就是重构定了monorepo与微前端架构后, 再晚一周, 期间重构和游戏并行开发
   - 预计游戏开发时长, 4周左右, 一周出原型, 两周开发, 一周完善
- 最近角色 白子 5.16 可以白子单车躲避障碍, 可惜已经有类似游戏了 https://bluearchive.jp/kourintaisai/game01/
- 游戏视频 https://www.bilibili.com/video/BV1uD4y1b7pY/?spm_id_from=333.337.search-card.all.click

### 具体操作

- 拆分新项目
- 使用前端游戏引擎, 例如 COCOS2D-X
- 小组分工, 能力储备
   - 动画, 原画 等美术方向, 预计 ai 加人工, 主方向为 像素 2d 游戏, 建立 ai 绘画流程规范
   - ui 设计
   - 前端开发
   - 后端, 流水线等
   - 产品设计, 抄一抄

**Comment by luckyray-fan** [comment]
- 附人气角色列表及生日
- 日奈 2月19日
- 梓 12月26日
- 爱丽丝 3月25日
- 优香 3月14日
- 星野 1月2日
- 168 11月16日
- 小春 4月16日
- 白子 5.16
- 日富美 11月27日
- 社长 3月12日

**Comment by luckyray-fan** [comment]
那游戏就是白子抓老师吧, 玩家操纵白子追老师, 抓到了就嘿嘿嘿, 先写这么一句话, 后期再补齐具体需求文档和开发技术方案

**Comment by notnotype** [comment]
好！100昏
