### ISSUE TITLE
[Bug] 好感剧情的“未开放”提示需修改展示逻辑

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#223]
### 问题描述

~~才发现还有写过提示（~~
只当指定剧情进入时才会显示提示
_指直接进入`./story/剧情编号`_
![image](https://user-images.githubusercontent.com/55832499/230750191-44fd8050-f7fb-4302-bfda-c740eec787c1.png)
进入目录时则不会显示
_指直接进入`./story`_
![image](https://user-images.githubusercontent.com/55832499/230750195-a1257188-344c-4386-90f1-431b6e060bcb.png)
并且图标明显变小↑

### 问题位置

./archive/*/story/*

### 复现流程

从momotalk中打开时就指定了剧情，打开有提示
直接点击上方目录即打开剧情目录，打开无提示

**Comment by mark9804** [comment]
/archive/story/ 我没有给 route，这个理论上应该是正常访问无法触及的，有生之年应该给一个404

图标宽度不一样的原因主要是因为错误信息长度不一样，这个错误信息挺神奇的，同样的代码，github.io 能正常显示错误，CloudFlare 上面的显示不出
