### ISSUE TITLE
[Bug] 超分开启后返回cdn地址错误

### ISSUE THREAD

**Issue by xiaofeiTM233** [Mark9804/blue-archive-story-viewer#225]
### 问题描述

![img](https://user-images.githubusercontent.com/55832499/230771495-9159a5f9-85db-49b6-9961-6fc40c532065.png)
![img](https://user-images.githubusercontent.com/55832499/230771484-64a1be74-3abe-4e21-8974-8b88aa187301.png)

### 问题位置

超分

### 复现流程

超分

**Comment by xiaofeiTM233** [comment]
超分按钮如果在按钮更新前有开启超分则不能自动选中
![image](https://user-images.githubusercontent.com/55832499/231950051-063cb31a-ff46-487f-bd77-e1da40639a8d.png)

./settings

非首次进入网站，打开设置页面

其实可以不用管（？），毕竟首次进入就会自动选中了，没选中的自己点一下就是

**Comment by mark9804** [comment]
低优先，现在应该大家都是false没事
