### ISSUE TITLE
[Bug] 剧情播放的宽度算法依然有问题

### ISSUE THREAD

**Issue by mark9804** [Mark9804/blue-archive-story-viewer#234]
### 问题描述

--

### 问题位置

--

**Comment by Zhaohui-Xu** [comment]
在剧情播放live2d的时候会有宽度不匹配的问题
问题位置：https://blue-archive.io/archive/10064/story/100643
图片链接：https://img1.imgtp.com/2023/05/13/FLFSffPr.png

**Comment by mark9804** [comment]
麻烦按照以下方式重置一下网站然后重试看看

[剧情站无法更新的处理方式 - 哔哩哔哩](https://www.bilibili.com/read/cv23090498)

> 在剧情播放live2d的时候会有宽度不匹配的问题 问题位置：https://blue-archive.io/archive/10064/story/100643 图片链接：https://img1.imgtp.com/2023/05/13/FLFSffPr.png
