### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 18631841828** [Mark9804/blue-archive-story-viewer#237]
### 问题描述

有些角色的剧情看不了   本人安卓手机  用无线网不行  用移动流量，电信流量观看都不行  有些角色能看  不知道原因出在哪里

### 问题位置

https://blue-archive.io/archive/10001/story/100012

**Comment by mark9804** [comment]
目前我们只有部分学生的剧情，具体学生可以在我们网站的更新日志里看到。给老师带来不便不好意思，之后会修复黑屏问题

**Comment by mark9804** [comment]
作为已知问题我这里就先关掉的，别急，都会有的
