### ISSUE TITLE
momotalk原始数据结构

### ISSUE THREAD

**Issue by mark9804** [Mark9804/blue-archive-story-viewer#24]
### `MessageGroupId`: `number`

暂时没想明白，不过是有规律的

`五位数学生 ID` + `00` + `2-3位数字`

例：

```json
{
    "MessageGroupId": 100040020,
    "Id": 3,
    "CharacterId": 10004,
}
```

同一个 `GroupId` 可能代表者同一个回复组

```json
{
    "MessageGroupId": 100040020,
      "Id": 3,
      "CharacterId": 10004,
      "MessageCondition": "Answer",
}
```

```json
{
    "MessageGroupId": 100040020,
    "Id": 4,
    "CharacterId": 10004,
    "MessageCondition": "Answer",
}
```

### `Id`: `number`

应该是 Message ID，目前可以认为是两个 list 里面的唯一标识符

### `CharacterId`: `number`

角色的 ID，参考 SchaleDB 的数据，这个项目里面也有：https://github.com/ba-archive/blue-archive-story-viewer/blob/master/public/config/yaml/students.yaml

### `MessageCondition`: `'None' | 'FavorRankUp' | 'Answer' | 'Feedback'`

目前发现有四种: `None`, `FavorRankUp`, `Answer`, `Feedback`

`FavorRankUp`: 好感度提升后，学生给老师发的第一条消息（在这一条消息上方显示“已读”横幅）

* 这条消息是不是可以作为momotalk的分割点？
  * 如果把这条消息作为momotalk分割点，那么标题应该从哪里取到？ - #23 数据流当中有

`Answer`: 老师给学生的回复

`Feedback`: 老师回复完成后，学生对老师发送的消息作出的反应

`None`: 应该是一般信息，接在 `FavorRankUp` 第一条信息后面，或者 `Feedback` 后面的学生发来的信息

### `ConditionValue`: `number`

我觉得是角色好感度等级到了这个等级之后解锁的意思

### `PreConditionGroupId`: `number`

需要完成前置MessageGroup 才能显示？

### `PreConditionFavorScheduleId`: `number`

代表好感剧情结束后紧接着的对话，**可以用来标记“已读信息”**

### `FavorScheduleId`: `number`

该值如果不为 `0`，则代表当前消息事件完成之后会立即接上一个好感事件入口。

该值的组成结构为 `五位数学生 ID` + `学生好感度等级`。

例：

```json
"FavorScheduleId": 100146,
```

则代表进入泉奈（学生 ID 10014）第六级好感度时的剧情。

### `NextGroupId`: `number`

这一组信息完成之后显示下一组信息

### `FeedbackTimeMillisec`: `number`

学生回复的时候会有一个“对方正在打字”的那个动画，这个字段控制了打字动画的时长

### `MessageType`: `'Text' | 'Image' | 'None'`

有三种取值：`Text`, `Image`, `None`

### `ImagePath`: `string`

如果 `MessageType` 是 `Image` 的话，此字段启用，记录图像文件位置。

### `MessageKR`, `MessageJP`: `string`

如果 `MessageType` 是 `Text` 的话，这两个字段启用。记录聊天文字的信息。

**Comment by Kanaricc** [comment]
`PreConditionFavorScheduleId` 看起来像是好感剧情结束后紧接着的对话。

进入事件前

<img width="275" alt="Snipaste_2022-10-24_22-00-26" src="https://user-images.githubusercontent.com/46213939/197544777-cf15fa6a-704f-449e-bbda-8d8609982e0f.png">

事件结束后的第一句话

<img width="273" alt="Snipaste_2022-10-24_22-00-59" src="https://user-images.githubusercontent.com/46213939/197544788-5f3800e3-1495-4a4b-a909-abd2e8a958da.png">

对应的 json

<img width="450" alt="Snipaste_2022-10-24_22-02-56" src="https://user-images.githubusercontent.com/46213939/197544789-9518e159-141a-4ebf-b747-99a9c909a0d1.png">

**Comment by mark9804** [comment]
很有可能

**Comment by notnotype** [comment]
MessageGroupId格式应该为
五位数学生 ID +两位数字 + 0
PreConditionGroupId指向上一个Group的MessageCondition为Answer的Group，表示该Group应该紧跟着老师的回复出现

**Comment by mark9804** [comment]
> MessageGroupId格式应该为 五位数学生 ID +两位数字 + 0 

准确的说，是补 `0` 补到两位数，比如说好感 6 级就是 `06`，好感 20 级 就是 `20`

> PreConditionGroupId指向上一个Group的MessageCondition为Answer的Group，表示该Group应该紧跟着老师的回复出现

不是的，比如

```json
{
      "MessageGroupId": 100040080,
      "Id": 12,
      "CharacterId": 10004,
      "MessageCondition": "Feedback",
      "ConditionValue": 0,
      "PreConditionGroupId": 0,
      "PreConditionFavorScheduleId": 0,
      "FavorScheduleId": 0,
      "NextGroupId": 100040090,
      "FeedbackTimeMillisec": 1000,
      "MessageType": "Text",
      "ImagePath": "",
      "MessageKR": "잘 자. 선생님.",
      "MessageJP": "おやすみ、先生",
      "MessageTH": "ฝันดีนะ.. คุณครู",
      "MessageTW": "好好睡吧。老師，",
      "MessageEN": "Goodnight, Sensei."
    },
    {
      "MessageGroupId": 100040090,
      "Id": 13,
      "CharacterId": 10004,
      "MessageCondition": "FavorRankUp",
      "ConditionValue": 3,
      "PreConditionGroupId": 100040080,
      "PreConditionFavorScheduleId": 0,
      "FavorScheduleId": 0,
      "NextGroupId": 100040100,
      "FeedbackTimeMillisec": 0,
      "MessageType": "Text",
      "ImagePath": "",
      "MessageKR": "선생님. 이번 휴일의 심야 시간에 시간 괜찮을까?",
      "MessageJP": "先生。今度の休みの日の深夜、時間ある？",
      "MessageTH": "คุณครู วันหยุดนี้คุณครูมีเวลาว่างช่วง\nดึกบ้างไหม?",
      "MessageTW": "老師，這次假日的深夜有空嗎？",
      "MessageEN": "Sensei, will you be free in the evening this weekend?"
    },
```

<img width="532" alt="image" src="https://user-images.githubusercontent.com/9006264/206479762-5e35c1dc-90a3-466a-83de-d4f0def75f6c.png">

我好像没用到这个值，目前应该也不用关注这个值是做什么的

**Comment by mark9804** [comment]
deprecated
