### ISSUE TITLE
剧情数据原始结构

### ISSUE THREAD

**Issue by ourandream** [Mark9804/blue-archive-story-viewer#26]
# ScriptKr

通常格式: `"3;호시노(星野, 立绘名);03(表情编号);剧情语句(可选)\n#3;效果或动作(可选)"`

`3`指立绘初始位置(共有五个, 可能因为动作移动). 

当为不是编号而是`#na`时, 有角色名则为人物说话但没有立绘, 无角色名表示旁白. 

一般剧情语句或效果后面会加`\n`作为分隔, 如果在字符串的末尾则不加.

`"#Title;XXX"`: 剧情标题

`"#Place;XXX"`: 左上提示切换地点, 可用于背景加载, 但注意有时没有提示, 所以应该有其他加载背景的方法.

`#`后接一个实体或操作, 指对实体进行的操作或者给操作设置的值. 具体格式为`#实体或操作;动作或值\n`

`#wait;1000\n`: 播放线程睡眠（等待） `1000ms`.

`#fontsize;80` 修改字体大小到 `80dp`

\++ `#zmc;`: 画面拉近

`#move;0,-222;2528;200\n`: 画面移动

\-- ~~`#zmc;move;0,-222;2528;200\n#3`: 画面拉近~~

\++ `#serial;`: 逐个字显示当前对话文字，通常和 `[wa: Number]` 配合，控制文字间的暂停，单位为 `ms`

\++ `#instant;`: 立刻显示完当前对话文字

\-- ~~`#zmc;instant;0,-222;2528\n`: 画面拉近后保持~~

`#all;hide`隐藏画面上的所有内容（包括控制按钮），只显示播放器底部的黑色背景（也可以认为是在播放器最上层加上一个黑色不透明遮罩），用于大转场

`#bgshake\n`: 背景左右摇动
`#hidemenu`: 消除菜单

`#3;动作\n`指人物动作, 目前知道的有:    

| 符号      | 动作              | 示例位置          | 备注            |
| ------- | --------------- | ------- | ------- |
| a       | 人物出现(从背影到立绘)   |       | 可以通过 `filter: brightness `控制？<br/>https://www.bilibili.com/video/av756548781/?p=8&t=308 这里的 `a`的作用是显示生气图标，再讨论 |
| d       | 人物离开            |             | disappear   |
| `dl` | 向左平移出屏幕 | https://www.bilibili.com/video/av756548781/?p=8&t=314 |  |
| `ar`? |  | https://www.bilibili.com/video/av756548781/?p=11&t=130 |  |
| hophop  | 跳动两下            |             |             |
| greeting | 屈膝礼（向下平移，暂停，归位） | https://www.bilibili.com/video/av756548781/?p=11&t=119 |  |
| shake   | 左右摇动            | https://www.bilibili.com/video/av756548781/?p=11&t=105 | 左右晃动？       |
| m2      | 移动到指定立绘位置, 可更改数字            |             | 位置取值为 `1`, `2`, `3`, `4`, `5` |
| stiff   | 小幅度左右移动         |          |          |
| closeup | 人物靠近(如果已经近处则不动) |  | “靠近”指靠近玩家位置 |
| jump    | 跳动一次            |             |             |
| `falldownR` | 以脚底为变换中心左右摆动，然后倒下 | https://www.bilibili.com/video/av756548781/?p=8&t=385 |  |

`#3;em;[반응]\n`: `[반응]`为效果, 它的前面还使用了em提示该人物作为重点(多人物时她相比其他人亮),目前知道的如下:

| 符号          | 效果                                                         | 示例                                                   | 机翻         |
| ------------- | ------------------------------------------------------------ | ------------------------------------------------------ | ------------ |
| `[하트]`; `h` | ![](https://cdn.staticaly.com/gh/ourandream/blog_images@master/20211101/2022-10-24-19-21-47-image.5l9sa2oh6wc0.webp) |                                                        | Heart（心）  |
| `[반응]`      | ![](https://cdn.staticaly.com/gh/ourandream/blog_images@master/20211101/2022-10-24-19-12-03-image.1j0irq02uiao.webp) | https://www.bilibili.com/video/av756548781/?p=11&t=191 | 反应         |
| `[음표]`; `m` | ![](https://cdn.staticaly.com/gh/ourandream/blog_images@master/20211101/2022-10-24-19-13-35-image.2d6z1a84gz8k.webp) | https://www.bilibili.com/video/av756548781/?p=11&t=216 | 音符 / music |
| `[반짝]`; `k` | ![](https://cdn.staticaly.com/gh/ourandream/blog_images@master/20211101/2022-10-24-19-14-56-image.5pt4xzgs3280.webp) | https://www.bilibili.com/video/av756548781/?p=11&t=165 | 闪光         |
| `[속상함]`; `u` | ![](https://cdn.staticaly.com/gh/ourandream/blog_images@master/20211101/2022-10-24-19-17-25-image.6lq43hf1kfs0.webp) | https://www.bilibili.com/video/av756548781/?p=8&t=373  | 沮丧         |
| `[땀]`; `w`   | ![](https://cdn.staticaly.com/gh/ourandream/blog_images@master/20211101/2022-10-24-19-20-05-image.2f3p8lyi7n0g.webp) | https://www.bilibili.com/video/av756548781/?p=11&t=126 | 流汗         |
| `[...]`       | ![image-20221026221224043](https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221026221224043.png) | https://www.bilibili.com/video/av756548781/?p=11&t=171 |              |
| `c`           | ![image-20221026221609211](https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221026221609211.png) | https://www.bilibili.com/video/av756548781/?p=11&t=130 |              |
| `[!]`         | ![image-20221026223556400](https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221026223556400.png) | https://www.bilibili.com/video/av756548781/?p=8&t=276  |              |
| `[빠직]`      | ![image-20221026223706812](https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221026223706812.png) | https://www.bilibili.com/video/av756548781/?p=8&t=281  |              |
| `[?!]`        | ![image-20221026230223534](https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221026230223534.png) | https://www.bilibili.com/video/av756548781/?p=8&t=364  |              |
| `[?]`         | ![image-20221026230652174](https://raw.githubusercontent.com/Mark9804/typora-image-repo/master/uPic/image-20221026230652174.png) | https://www.bilibili.com/video/av756548781/?p=8&t=393  |              |

## 注音特效： `[ruby=xxx]yyy[/ruby]`
<img width="284" alt="image" src="https://user-images.githubusercontent.com/9006264/198049532-8d4738a4-e32a-4f8f-92fa-1e28728d9148.png">

`"[s1] \"分支1\"\n[s2] \"分支2\""`: 选择分支, 对应后面`SelectionGroup`的, 无对话框时s改为`ns`.

1, 2.档为`s`时只有一个选项.

live2d语句或无对话框剧情语句大概如下:

`#st;[-1200,-530];serial;60;[wa:900]― 모처럼이니 [wa:2450]선생님도 어떠신가요?`
`#st`放置文字(有时也用于消除对话框), `[wa:number]`为放置时中间的停顿, `serial`指缓慢显示文字, `instant`是立即显示.`60`应该是指字体大小.
`#clearST`为取消放置文字
``
# 其他属性

`BGMId`,: 不为0时播放bgm.
`BGName`: 背景图片id(也可以是cg), 通过ScenarioBGNameExcelTable.json匹配
`BGEffect`: 背景效果(如粉尘), 通过ScenarioBGEffectExcelTable.json匹配
`Transition`: 变换(如画面渐变), 通过ScenarioTransitionExcelTable.json匹配
`Sound`:不为null时播放效果音或语音

**Comment by mark9804** [comment]
对策委员会最后迎接星野回家的那段剧情出现了大量的 `#clearST`，另外有一个 `smooth;` 属性猜测是用于控制效果平滑度的，约等于 css 当中的 `animation-timing-function: linear;`

**Comment by mark9804** [comment]
deprecated
