### ISSUE TITLE
玩家姓名输入框长度不好控制

### ISSUE THREAD

**Issue by mark9804** [Mark9804/blue-archive-story-viewer#68]
`input` 标签计算长度（特别英文长度）的时候有点问题，可能要用一个 `div contenteditable` 标签去模拟输入然后监听变化，有大手子有想法吗

<img width="182" alt="image" src="https://user-images.githubusercontent.com/9006264/208943607-1f4fdd38-38bd-4938-9ca2-b9c8bf7f4e77.png">

**Comment by ourandream** [comment]
用div contenteditable和v-model自己实现一个input？几行代码的事

**Comment by Mark9804** [comment]
原来还有一个 `@input` 事件，我是猪鼻

**Comment by mark9804** [comment]
`contenteditable` 在 Safari 上不论中英文都会出现文字只能倒序输入的问题，四舍五入 iPhone iPad 全寄了

> 用div contenteditable和v-model自己实现一个input？几行代码的事
